spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:mariadb://svc.sel5.cloudtype.app:30261/gowo?createDatabaseIfNotExist=true
    username: root
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver

